name: Auto Publish to npm

on:
  push:
    branches:
      - main  # triggers on pushes to main branch

jobs:
  auto-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push tags

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Bump version automatically
      - name: Bump version
        id: bump_version
        run: |
          # Use npm version patch/minor/major as needed
          NEW_VERSION=$(npm version patch -m "Release %s")
          echo "New version: $NEW_VERSION"
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Build your package
      - name: Build
        run: npm run build

      # 6️⃣ Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
