name: Auto Semantic Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ allows pushing commits and tags back to the repo

jobs:
  auto-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to fetch tags and push commits

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Determine semantic version bump
      - name: Determine version bump
        id: semver
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=%B)
          echo "Commits since last tag: $COMMITS"

          if echo "$COMMITS" | grep -q 'BREAKING CHANGE'; then
            VERSION_BUMP="major"
          elif echo "$COMMITS" | grep -q '^feat:'; then
            VERSION_BUMP="minor"
          else
            VERSION_BUMP="patch"
          fi

          echo "VERSION_BUMP=$VERSION_BUMP" >> $GITHUB_OUTPUT

      # 5️⃣ Bump version safely and push back to GitHub
      - name: Bump version
        run: |
          npm version ${{ steps.semver.outputs.VERSION_BUMP }} --no-git-tag-version

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "Automated release v$(node -p "require('./package.json').version")"
          git tag v$(node -p "require('./package.json').version")
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Build package
      #- name: Build
      #  run: npm run build

      # 7️⃣ Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
